#!/bin/bash

#rm $HOME/.minimal-tex.tex
rm .minimal-tex.tex

if [ -z $1 ]
then
	echo "Usage:"
	echo
	echo "	minimal-tex file"
	echo
else

#cat << EOF > $HOME/.minimal-tex.tex
cat << EOF > .minimal-tex.tex
\documentclass{article}
\begin{document}
\hoffset=-1in
\voffset=-1in
\setbox0\hbox{\begin{tabular}{l}
\\\\
EOF

cp $1 .$1-tex
gsed -i 's/^/\\tt\{/g' .$1-tex
gsed -i 's/$/\}/g' .$1-tex
gsed -i 's/$/\\\\/g' .$1-tex

#cat .$1-tex >> $HOME/.minimal-tex.tex
cat .$1-tex >> .minimal-tex.tex

#cat << EOF >> $HOME/.minimal-tex.tex
cat << EOF >> .minimal-tex.tex
\end{tabular}}
\pdfpageheight=\dimexpr\ht0+\dp0\relax
\pdfpagewidth=\wd0
\shipout\box0
\stop
EOF

#pdflatex $HOME/.minimal-tex.tex
#cp $HOME/.minimal-tex.pdf $1.pdf
#open $1.pdf
#rm $HOME/.minimal-tex.a*
#rm $HOME/.minimal-tex.l*
#rm $HOME/.minimal-tex.t*
#rm $HOME/.minimal-tex.p*

pdflatex .minimal-tex.tex
cp .minimal-tex.pdf $1.pdf
open $1.pdf
rm .minimal-tex.a*
rm .minimal-tex.l*
rm .minimal-tex.t*
rm .minimal-tex.p*

echo "Your pdf has been created at '$1.pdf'."
fi
